version: '3'

services:
  php:
    build:
      context: '.'
      dockerfile: 'Dockerfile-php'
      args:
        uid: 1000
    restart: always
    depends_on:
      - mysql
    ports:
      - 80:80
    volumes:
      - /var/www/html/vendor
      - ./test:/var/www/html

  mysql:
    image: mysql
    volumes:
      - ./.docker/mysql/docker-entrypoint-initdb.d/test.sql:/docker-entrypoint-initdb.d/test.sql
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
volumes:
  dbdata: